django:
  build: .

  environment:
    DJANGO_SETTINGS_MODULE: config.settings
    DB_HOST: postgres
    DB_NAME: postgres

  ports:
    - "8000:80"

  links:
    - postgres

postgres:
  image: postgres
