version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .

    env_file: .env

    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"

    links:
      - postgres

    volumes:
      - .:/project
      - ./backups:/backups

    command: /project/bin/uwsgi.sh

  postgres:
    env_file: .env
    image: postgres:9.6

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
      - ./backups:/db_backups

{% if cookiecutter.celery == 'y' %}
  celery:
    build:
      context: .
    env_file: .env
    command: celery worker -l info -b amqp://user:user@rabbit:5672// -A config.celery_config
    volumes:
      - .:/project
    links:
      - postgres
      - rabbit

  rabbit:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
{% endif %}
