version: '2'

services:
  django:
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: config.env.production

  postgres:
    restart: always

{% if cookiecutter.celery == 'y' %}
  celery:
    restart: always

  rabbit:
    restart: always
{% endif %}
